package com.testes.multi_instance;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class AnaliseTecnicaDO implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("Parecer")
	private java.lang.String parecer;
	@org.kie.api.definition.type.Label("Análise favorável?")
	private java.lang.Boolean favoravel;
	private static final java.lang.String PATTERN = "[ %s ] %s";

	public AnaliseTecnicaDO() {
	}

	public java.lang.String getParecer() {
		return this.parecer;
	}

	public void setParecer(java.lang.String parecer) {
		this.parecer = parecer;
	}

	public java.lang.Boolean getFavoravel() {
		return this.favoravel;
	}

	public void setFavoravel(java.lang.Boolean favoravel) {
		this.favoravel = favoravel;
	}

	public AnaliseTecnicaDO(java.lang.String parecer,
			java.lang.Boolean favoravel) {
		this.parecer = parecer;
		this.favoravel = favoravel;
	}

    @java.lang.Override
    public java.lang.String toString() {
        return java.lang.String.format(PATTERN, favoravel, parecer);
    }

}