package com.testes.multi_instance;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class InputDO implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label(value = "Precisa de análise?")
	private java.lang.Boolean precisaAnalise;
	@org.kie.api.definition.type.Label(value = "Áreas Técnicas")
	private java.util.List<java.lang.String> areas;

	public InputDO() {
	}

	public java.lang.Boolean getPrecisaAnalise() {
		return this.precisaAnalise;
	}

	public void setPrecisaAnalise(java.lang.Boolean precisaAnalise) {
		this.precisaAnalise = precisaAnalise;
	}

	public java.util.List<java.lang.String> getAreas() {
		return this.areas;
	}

	public void setAreas(java.util.List<java.lang.String> areas) {
		this.areas = areas;
	}

	public InputDO(java.lang.Boolean precisaAnalise,
			java.util.List<java.lang.String> areas) {
		this.precisaAnalise = precisaAnalise;
		this.areas = areas;
	}

}