package com.testes.multi_instance;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class ResumoDO implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label(value = "Solicitação")
	private com.testes.multi_instance.InputDO solicitacao;
	@org.kie.api.definition.type.Label(value = "Analises")
	private java.util.List<com.testes.multi_instance.AnaliseTecnicaDO> analises;

	public ResumoDO() {
	}

	public com.testes.multi_instance.InputDO getSolicitacao() {
		return this.solicitacao;
	}

	public void setSolicitacao(com.testes.multi_instance.InputDO solicitacao) {
		this.solicitacao = solicitacao;
	}

	public java.util.List<com.testes.multi_instance.AnaliseTecnicaDO> getAnalises() {
		return this.analises;
	}

	public void setAnalises(
			java.util.List<com.testes.multi_instance.AnaliseTecnicaDO> analises) {
		this.analises = analises;
	}

	public ResumoDO(com.testes.multi_instance.InputDO solicitacao,
			java.util.List<com.testes.multi_instance.AnaliseTecnicaDO> analises) {
		this.solicitacao = solicitacao;
		this.analises = analises;
	}

}